### PR TITLE
Add some language to the README explaining what NoDL is

### PR DESCRIPTION
**Pull request by emersonknapp**
I had heard it referenced but had a hard time figuring out what this project was - major marketing problem! I just added some basic language to the README to clarify a little bit what's here and where to learn more.

### CODE REVIEW

**Review by aprotyas — APPROVED** [review]

**Comment by emersonknapp** [comment]
Ping - wanna just merge it? I think the tests won't run until someone with more permissions explicitly allows it

**Review by artivis — APPROVED** [review]

**Comment by artivis** [comment]
Hey there,
the CI fails on rosdep, possibly because Rolling is on transition, I'll look into it asap.

**Comment by emersonknapp** [comment]
@artivis want to just merge this? again, it's not a code change. 

related question - is this project live? Is there active development on it, or is it an abandoned experiment?

**Comment by emersonknapp** [comment]
I'm going to close this, assuming that the project is abandoned

**Comment by artivis** [comment]
@emersonknapp my apologies, I totally missed your summer ping. You right I could merge this straight away if you were to re-open it.

**Pull request merged**
